/**
 * Bilingual label catalog for every user-facing enum. Values are stored in the
 * database as English keys; clients render labels in the requested language,
 * which makes runtime language switching purely presentational.
 */

export interface EnumEntry {
  value: string;
  en: string;
  bn: string;
}

export const ENUM_CATALOG: Record<string, EnumEntry[]> = {
  gender: [
    { value: 'MALE', en: 'Male', bn: 'পাত্র' },
    { value: 'FEMALE', en: 'Female', bn: 'পাত্রী' },
  ],
  profileMode: [
    { value: 'ISLAMIC', en: 'Islamic Matrimony', bn: 'ইসলামিক ম্যাট্রিমনি' },
    { value: 'GENERAL', en: 'General Matrimony', bn: 'সাধারণ ম্যাট্রিমনি' },
  ],
  maritalStatus: [
    { value: 'NEVER_MARRIED', en: 'Never Married', bn: 'অবিবাহিত' },
    { value: 'MARRIED', en: 'Married', bn: 'বিবাহিত' },
    { value: 'DIVORCED', en: 'Divorced', bn: 'ডিভোর্সড' },
    { value: 'WIDOWED', en: 'Widowed', bn: 'বিধবা' },
    { value: 'WIDOWER', en: 'Widower', bn: 'বিপত্নীক' },
  ],
  complexion: [
    { value: 'VERY_FAIR', en: 'Very Fair', bn: 'অত্যন্ত ফর্সা' },
    { value: 'FAIR', en: 'Fair', bn: 'ফর্সা' },
    { value: 'MEDIUM', en: 'Medium', bn: 'শ্যামলা' },
    { value: 'OLIVE', en: 'Olive', bn: 'উজ্জ্বল শ্যামলা' },
    { value: 'DARK', en: 'Dark', bn: 'কালো' },
  ],
  bloodGroup: [
    { value: 'A_POS', en: 'A+', bn: 'এ পজিটিভ' },
    { value: 'A_NEG', en: 'A-', bn: 'এ নেগেটিভ' },
    { value: 'B_POS', en: 'B+', bn: 'বি পজিটিভ' },
    { value: 'B_NEG', en: 'B-', bn: 'বি নেগেটিভ' },
    { value: 'AB_POS', en: 'AB+', bn: 'এবি পজিটিভ' },
    { value: 'AB_NEG', en: 'AB-', bn: 'এবি নেগেটিভ' },
    { value: 'O_POS', en: 'O+', bn: 'ও পজিটিভ' },
    { value: 'O_NEG', en: 'O-', bn: 'ও নেগেটিভ' },
    { value: 'UNKNOWN', en: 'Unknown', bn: 'জানা নেই' },
  ],
  educationLevel: [
    { value: 'BELOW_SSC', en: 'Below SSC', bn: 'এসএসসির নিচে' },
    { value: 'SSC', en: 'SSC', bn: 'এসএসসি' },
    { value: 'HSC', en: 'HSC', bn: 'এইচএসসি' },
    { value: 'DIPLOMA', en: 'Diploma', bn: 'ডিপ্লোমা' },
    { value: 'BACHELORS', en: "Bachelor's", bn: 'স্নাতক' },
    { value: 'MASTERS', en: "Master's", bn: 'স্নাতকোত্তর' },
    { value: 'DOCTORATE', en: 'Doctorate', bn: 'ডক্টরেট' },
    { value: 'MADRASA_QAWMI', en: 'Qawmi Madrasa', bn: 'কওমি মাদ্রাসা' },
    { value: 'MADRASA_ALIA', en: 'Alia Madrasa', bn: 'আলিয়া মাদ্রাসা' },
    { value: 'HAFEZ', en: 'Hafez', bn: 'হাফেজ' },
    { value: 'ALIM', en: 'Alim', bn: 'আলিম' },
    { value: 'OTHER', en: 'Other', bn: 'অন্যান্য' },
  ],
  familyStatus: [
    { value: 'LOWER_CLASS', en: 'Lower Class', bn: 'নিম্নবিত্ত' },
    { value: 'LOWER_MIDDLE_CLASS', en: 'Lower Middle Class', bn: 'নিম্ন মধ্যবিত্ত' },
    { value: 'MIDDLE_CLASS', en: 'Middle Class', bn: 'মধ্যবিত্ত' },
    { value: 'UPPER_MIDDLE_CLASS', en: 'Upper Middle Class', bn: 'উচ্চ মধ্যবিত্ত' },
    { value: 'UPPER_CLASS', en: 'Upper Class', bn: 'উচ্চবিত্ত' },
  ],
  familyValues: [
    { value: 'TRADITIONAL', en: 'Traditional', bn: 'ঐতিহ্যবাহী' },
    { value: 'MODERATE', en: 'Moderate', bn: 'মধ্যপন্থী' },
    { value: 'LIBERAL', en: 'Liberal', bn: 'উদারপন্থী' },
    { value: 'RELIGIOUS', en: 'Religious', bn: 'ধার্মিক' },
  ],
  religion: [
    { value: 'ISLAM', en: 'Islam', bn: 'ইসলাম' },
    { value: 'HINDUISM', en: 'Hinduism', bn: 'হিন্দু' },
    { value: 'CHRISTIANITY', en: 'Christianity', bn: 'খ্রিস্টান' },
    { value: 'BUDDHISM', en: 'Buddhism', bn: 'বৌদ্ধ' },
    { value: 'OTHER', en: 'Other', bn: 'অন্যান্য' },
  ],
  aqidah: [
    {
      value: 'AHLE_SUNNAH_WAL_JAMAAH',
      en: 'Ahle Sunnah Wal Jamaah',
      bn: 'আহলে সুন্নাহ ওয়াল জামাআহ',
    },
    { value: 'SALAFI', en: 'Salafi', bn: 'সালাফি' },
    { value: 'DEOBANDI', en: 'Deobandi', bn: 'দেওবন্দি' },
    { value: 'BARELVI', en: 'Barelvi', bn: 'বেরলভি' },
    { value: 'OTHER', en: 'Other', bn: 'অন্যান্য' },
  ],
  madhhab: [
    { value: 'HANAFI', en: 'Hanafi', bn: 'হানাফি' },
    { value: 'SHAFII', en: "Shafi'i", bn: 'শাফেয়ি' },
    { value: 'MALIKI', en: 'Maliki', bn: 'মালিকি' },
    { value: 'HANBALI', en: 'Hanbali', bn: 'হাম্বলি' },
    { value: 'AHLE_HADITH', en: 'Ahle Hadith', bn: 'আহলে হাদিস' },
    { value: 'NONE', en: 'No specific madhhab', bn: 'নির্দিষ্ট মাযহাব নেই' },
  ],
  prayerFrequency: [
    { value: 'FIVE_TIMES_DAILY', en: 'Five times daily', bn: 'পাঁচ ওয়াক্ত' },
    { value: 'MOSTLY', en: 'Mostly', bn: 'প্রায়ই পড়া হয়' },
    { value: 'SOMETIMES', en: 'Sometimes', bn: 'মাঝে মাঝে' },
    { value: 'RARELY', en: 'Rarely', bn: 'কদাচিৎ' },
    { value: 'NEVER', en: 'Never', bn: 'পড়া হয় না' },
  ],
  beardStyle: [
    { value: 'FULL_SUNNAH', en: 'Full Sunnah beard', bn: 'সুন্নতি দাড়ি' },
    { value: 'TRIMMED', en: 'Trimmed', bn: 'ছোট করে ছাঁটা' },
    { value: 'NONE', en: 'No beard', bn: 'দাড়ি নেই' },
  ],
  hijabStyle: [
    { value: 'NIQAB_WITH_ABAYA', en: 'Niqab with Abaya', bn: 'নিকাবসহ বোরকা' },
    { value: 'HIJAB_WITH_ABAYA', en: 'Hijab with Abaya', bn: 'হিজাবসহ বোরকা' },
    { value: 'HIJAB_ONLY', en: 'Hijab only', bn: 'শুধু হিজাব' },
    { value: 'MODEST_DRESS', en: 'Modest dress', bn: 'শালীন পোশাক' },
    { value: 'NONE', en: 'None', bn: 'পর্দা করা হয় না' },
  ],
  quranMemorization: [
    { value: 'FULL_HAFEZ', en: 'Full Hafez', bn: 'সম্পূর্ণ হাফেজ' },
    { value: 'MULTIPLE_JUZ', en: 'Multiple Juz', bn: 'কয়েক পারা' },
    { value: 'FEW_SURAHS', en: 'Few Surahs', bn: 'কয়েকটি সূরা' },
    { value: 'LEARNING', en: 'Currently learning', bn: 'শিখছি' },
    { value: 'NONE', en: 'None', bn: 'মুখস্থ নেই' },
  ],
  quranRecitation: [
    { value: 'FLUENT_WITH_TAJWEED', en: 'Fluent with Tajweed', bn: 'তাজবিদসহ সহিহ তিলাওয়াত' },
    { value: 'FLUENT', en: 'Fluent', bn: 'সাবলীল তিলাওয়াত' },
    { value: 'LEARNING', en: 'Learning', bn: 'শিখছি' },
    { value: 'CANNOT_READ', en: 'Cannot read', bn: 'পড়তে পারি না' },
  ],
  polygynyPreference: [
    { value: 'ACCEPTABLE', en: 'Acceptable', bn: 'সম্মত' },
    { value: 'NOT_ACCEPTABLE', en: 'Not acceptable', bn: 'সম্মত নই' },
    { value: 'CONDITIONAL', en: 'Conditional', bn: 'শর্তসাপেক্ষ' },
    { value: 'NOT_APPLICABLE', en: 'Not applicable', bn: 'প্রযোজ্য নয়' },
  ],
  viewsOnLoans: [
    { value: 'AVOID', en: 'Avoid loans', bn: 'ঋণ এড়িয়ে চলি' },
    { value: 'NECESSARY_ONLY', en: 'Necessary only', bn: 'প্রয়োজনে মাত্র' },
    { value: 'FLEXIBLE', en: 'Flexible', bn: 'নমনীয়' },
  ],
  guardianRelation: [
    { value: 'FATHER', en: 'Father', bn: 'পিতা' },
    { value: 'MOTHER', en: 'Mother', bn: 'মাতা' },
    { value: 'BROTHER', en: 'Brother', bn: 'ভাই' },
    { value: 'SISTER', en: 'Sister', bn: 'বোন' },
    { value: 'UNCLE', en: 'Uncle', bn: 'চাচা/মামা' },
    { value: 'GRANDFATHER', en: 'Grandfather', bn: 'দাদা/নানা' },
    { value: 'OTHER', en: 'Other', bn: 'অন্যান্য' },
  ],
  smokingHabit: [
    { value: 'NEVER', en: 'Never', bn: 'কখনো না' },
    { value: 'OCCASIONALLY', en: 'Occasionally', bn: 'মাঝে মাঝে' },
    { value: 'REGULARLY', en: 'Regularly', bn: 'নিয়মিত' },
    { value: 'QUIT', en: 'Quit', bn: 'ছেড়ে দিয়েছি' },
  ],
  drinkingHabit: [
    { value: 'NEVER', en: 'Never', bn: 'কখনো না' },
    { value: 'OCCASIONALLY', en: 'Occasionally', bn: 'মাঝে মাঝে' },
    { value: 'REGULARLY', en: 'Regularly', bn: 'নিয়মিত' },
    { value: 'QUIT', en: 'Quit', bn: 'ছেড়ে দিয়েছি' },
  ],
  dietPreference: [
    { value: 'HALAL_ONLY', en: 'Halal only', bn: 'শুধুমাত্র হালাল' },
    { value: 'VEGETARIAN', en: 'Vegetarian', bn: 'নিরামিষভোজী' },
    { value: 'NON_VEGETARIAN', en: 'Non-vegetarian', bn: 'আমিষভোজী' },
    { value: 'VEGAN', en: 'Vegan', bn: 'ভেগান' },
    { value: 'NO_PREFERENCE', en: 'No preference', bn: 'কোনো পছন্দ নেই' },
  ],
  profileVisibility: [
    { value: 'PUBLIC', en: 'Public', bn: 'সবার জন্য উন্মুক্ত' },
    { value: 'VERIFIED_ONLY', en: 'Verified members only', bn: 'শুধুমাত্র ভেরিফাইড সদস্য' },
    { value: 'HIDDEN', en: 'Hidden', bn: 'লুকানো' },
  ],
  photoPolicy: [
    { value: 'VISIBLE', en: 'Visible to all', bn: 'সবার জন্য দৃশ্যমান' },
    { value: 'BLURRED', en: 'Blurred', bn: 'ঝাপসা' },
    { value: 'ON_ACCEPT', en: 'After interest accepted', bn: 'আগ্রহ গৃহীত হলে' },
    { value: 'ON_UNLOCK', en: 'After unlock', bn: 'আনলকের পরে' },
  ],
  contactPolicy: [
    { value: 'ON_UNLOCK', en: 'After unlock', bn: 'আনলকের পরে' },
    { value: 'ON_ACCEPT', en: 'After interest accepted', bn: 'আগ্রহ গৃহীত হলে' },
    { value: 'VERIFIED_ONLY', en: 'Verified members only', bn: 'শুধুমাত্র ভেরিফাইড সদস্য' },
  ],
  memberRelationship: [
    { value: 'SELF', en: 'Self', bn: 'নিজে' },
    { value: 'FATHER', en: 'Father', bn: 'পিতা' },
    { value: 'MOTHER', en: 'Mother', bn: 'মাতা' },
    { value: 'BROTHER', en: 'Brother', bn: 'ভাই' },
    { value: 'SISTER', en: 'Sister', bn: 'বোন' },
    { value: 'GUARDIAN', en: 'Guardian', bn: 'অভিভাবক' },
  ],
  interestStatus: [
    { value: 'PENDING', en: 'Pending', bn: 'অপেক্ষমাণ' },
    { value: 'ACCEPTED', en: 'Accepted', bn: 'গৃহীত' },
    { value: 'REJECTED', en: 'Rejected', bn: 'প্রত্যাখ্যাত' },
    { value: 'WITHDRAWN', en: 'Withdrawn', bn: 'প্রত্যাহৃত' },
  ],
  journeyStage: [
    { value: 'ACCEPTED', en: 'Interest Accepted', bn: 'আগ্রহ গৃহীত' },
    { value: 'FAMILY_DISCUSSION', en: 'Family Discussion', bn: 'পারিবারিক আলোচনা' },
    { value: 'MEETING', en: 'Meeting', bn: 'সাক্ষাৎ' },
    { value: 'ENGAGEMENT', en: 'Engagement', bn: 'এনগেজমেন্ট' },
    { value: 'MARRIED', en: 'Married', bn: 'বিবাহ সম্পন্ন' },
    { value: 'DISCONTINUED', en: 'Discontinued', bn: 'বন্ধ হয়েছে' },
  ],
  verificationType: [
    { value: 'EMAIL', en: 'Email Verified', bn: 'ইমেইল ভেরিফাইড' },
    { value: 'PHONE', en: 'Phone Verified', bn: 'ফোন ভেরিফাইড' },
    { value: 'NID', en: 'NID Verified', bn: 'এনআইডি ভেরিফাইড' },
    { value: 'FACE', en: 'Face Verified', bn: 'ফেস ভেরিফাইড' },
    { value: 'SCHOLAR', en: 'Scholar Verified', bn: 'স্কলার ভেরিফাইড' },
    { value: 'GUARDIAN', en: 'Guardian Verified', bn: 'অভিভাবক ভেরিফাইড' },
  ],
  unlockType: [
    { value: 'CONTACT', en: 'Contact Information', bn: 'যোগাযোগের তথ্য' },
    { value: 'GUARDIAN', en: 'Guardian Information', bn: 'অভিভাবকের তথ্য' },
    { value: 'FULL_BIODATA', en: 'Full Biodata', bn: 'সম্পূর্ণ বায়োডাটা' },
  ],
  profession: [
    { value: 'STUDENT', en: 'Student', bn: 'ছাত্র/ছাত্রী' },
    { value: 'HOMEMAKER', en: 'Homemaker', bn: 'গৃহিণী' },
    { value: 'BUSINESS', en: 'Business', bn: 'ব্যবসা' },
    { value: 'PRIVATE_JOB', en: 'Private Job', bn: 'প্রাইভেট জব' },
    { value: 'GOVT_JOB', en: 'Government Job', bn: 'সরকারি চাকুরীজীবী' },
    { value: 'DOCTOR', en: 'Doctor', bn: 'ডাক্তার' },
    { value: 'ENGINEER', en: 'Engineer', bn: 'ইঞ্জিনিয়ার' },
    { value: 'TEACHER_SCHOOL', en: 'School Teacher', bn: 'স্কুলের শিক্ষক' },
    { value: 'TEACHER_MADRASA', en: 'Madrasa Teacher', bn: 'মাদ্রাসার শিক্ষক' },
    { value: 'UNIVERSITY_TEACHER', en: 'University Teacher', bn: 'বিশ্ববিদ্যালয়ের শিক্ষক' },
    { value: 'FREELANCER', en: 'Freelancer', bn: 'ফ্রিল্যান্সার' },
    { value: 'IMAM_KHATIB', en: 'Imam / Khatib', bn: 'ইমাম/খতিব' },
    { value: 'LAWYER', en: 'Lawyer', bn: 'উকিল' },
    { value: 'NURSE', en: 'Nurse', bn: 'নার্স' },
    { value: 'JOURNALIST', en: 'Journalist', bn: 'সাংবাদিক' },
    { value: 'DEFENSE', en: 'Army / Navy / Air Force', bn: 'সেনা/নৌ/বিমানবাহিনী' },
    { value: 'POLICE_SECURITY', en: 'Police / Security Forces', bn: 'পুলিশ/নিরাপত্তা বাহিনী' },
    { value: 'AGRICULTURE', en: 'Agriculture', bn: 'কৃষি' },
    { value: 'EXPATRIATE', en: 'Expatriate Worker', bn: 'প্রবাসী' },
    { value: 'DRIVER', en: 'Driver', bn: 'ড্রাইভিং' },
    { value: 'UNEMPLOYED', en: 'Unemployed', bn: 'বেকার' },
    { value: 'OTHER', en: 'Other', bn: 'অন্যান্য' },
  ],
};
